apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamwizard-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onekigndom-backend
  template:
    metadata:
      annotations:
        # linkerd.io/inject: enabled  # This annotation enables automatic injection
      labels:
        app: streamwizard-backend
    spec:
      containers:
        - name: streamwizard-backend
          image: ghcr.io/onekingdom/onekingdom-bot:61743752e9b1451fef7b13232c5211adef31c545
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: onekingdom-backend
