apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamwizard-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onekigndom-backend
  template:
    metadata:
      annotations:
        # linkerd.io/inject: enabled  # This annotation enables automatic injection
      labels:
        app: streamwizard-backend
    spec:
      containers:
        - name: streamwizard-backend
          image: ghcr.io/onekingdom/onekingdom-bot:3db7570cd1aee8aae72c1c5612013164a1ed5891
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: onekingdom-backend
